// <auto-generated>
// This code was generated by a tool. Any changes made manually will be lost.
// </auto-generated>
namespace VAutomationCore.Properties
{
    /// <summary>
    /// A class for accessing resource files.
    /// </summary>
    internal sealed class Resources
    {
        private static readonly global::System.Resources.ResourceManager resourceMan;
        
        static Resources()
        {
            resourceMan = new global::System.Resources.ResourceManager("VAutomationCore.Properties.Resources", typeof(Resources).Assembly);
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance.
        /// </summary>
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                return resourceMan;
            }
        }
    }
}
